services:
  - type: web
    name: aqi-dashboard
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --chdir flask app:app
    envVars:
      - key: FLASK_DEBUG
        value: 0
      - key: PORT
        value: 10000
    healthCheckPath: /
    plan: free
    autoDeploy: true
