services:
  - type: web
    name: aqi-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask.app:app
    envVars:
      - key: FLASK_DEBUG
        value: 0
      - key: PORT
        value: 10000
    healthCheckPath: /
    plan: free
    autoDeploy: true
